### ISSUE TITLE
Add subtasks and Parents to graph (as option?)

### ISSUE THREAD

**Issue by perolo** [jeanarcand/foresight#15]
With the new REST Api Subtask is quite easy, but parent(to subtask) still not available(!?).
Experimented with similar plugin using graphviz - but this tool a lot better looking - I like it!

**Comment by jeanarcand** [comment]
Greetings Perolo,

That's pretty much what I did in #10 but it's for 0.8.1 which is to be released in the next few days. Basically it's an option that allows you to add all the "system links" which includes the parent to child dependency.

If it's what you meant I'll close this one as duplicate of #10.

Thanks

**Comment by perolo** [comment]
When I was plying around with the graphviz hierarchy plugin the "dot"-veiw gives a very hierarchical view of the dependencies - The D3-view is quite "cloud-like" view - Not sure which one I prefer...
